SQL:
  host: "localhost"
  db-user: "minecraft"
  user: "minecraft"
  log: "123"
#

redis:
  host: "localhost"
  port: "6379"
  auth: ""
  thischannel: ""
  debug: false
#

other:
  join_server_name: ""
#